image: rust:latest

before_script:
  - export PATH="$PATH:$CI_PROJECT_DIR/cargo/bin"
  - mdbook --version || cargo install --debug mdbook
pages:
  script:
    - mdbook build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
